fix: disable mysql tests

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -69,18 +69,18 @@ jobs:
           --health-retries 5
         ports:
           - 5432:5432
-      mysql:
-        image: mysql
-        env:
-          MYSQL_ROOT_PASSWORD: mysql
-          MYSQL_DATABASE: mysql
-        options: >-
-          --health-cmd "mysqladmin ping -h localhost"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 3306:3306
+#      mysql:
+#        image: mysql
+#        env:
+#          MYSQL_ROOT_PASSWORD: mysql
+#          MYSQL_DATABASE: mysql
+#        options: >-
+#          --health-cmd "mysqladmin ping -h localhost"
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
+#        ports:
+#          - 3306:3306
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -152,26 +152,26 @@ jobs:
               exit 1
           fi
 
-      - name: Test backend with MySQL
-        if: success() || steps.sqlite.conclusion == 'failure' || steps.postgres.conclusion == 'failure'
-        run: |
-          cd backend
-          export DATABASE_URL=mysql://root:mysql@localhost:3306/mysql
-          WEBUI_SECRET_KEY=secret-key GLOBAL_LOG_LEVEL=debug uvicorn main:app --port "8083" --forwarded-allow-ips '*' &
-          UVICORN_PID=$!
-          # Wait up to 20 seconds for the server to start
-          for i in {1..20}; do
-              curl -s http://localhost:8083/api/config > /dev/null && break
-              sleep 1
-              if [ $i -eq 20 ]; then
-                  echo "Server failed to start"
-                  kill -9 $UVICORN_PID
-                  exit 1
-              fi
-          done
-          # Check that the server is still running after 5 seconds
-          sleep 5
-          if ! kill -0 $UVICORN_PID; then
-              echo "Server has stopped"
-              exit 1
-          fi
+#      - name: Test backend with MySQL
+#        if: success() || steps.sqlite.conclusion == 'failure' || steps.postgres.conclusion == 'failure'
+#        run: |
+#          cd backend
+#          export DATABASE_URL=mysql://root:mysql@localhost:3306/mysql
+#          WEBUI_SECRET_KEY=secret-key GLOBAL_LOG_LEVEL=debug uvicorn main:app --port "8083" --forwarded-allow-ips '*' &
+#          UVICORN_PID=$!
+#          # Wait up to 20 seconds for the server to start
+#          for i in {1..20}; do
+#              curl -s http://localhost:8083/api/config > /dev/null && break
+#              sleep 1
+#              if [ $i -eq 20 ]; then
+#                  echo "Server failed to start"
+#                  kill -9 $UVICORN_PID
+#                  exit 1
+#              fi
+#          done
+#          # Check that the server is still running after 5 seconds
+#          sleep 5
+#          if ! kill -0 $UVICORN_PID; then
+#              echo "Server has stopped"
+#              exit 1
+#          fi
